framework:
    secret: '%env(APP_SECRET)%'
    session: true

    csrf_protection:
        enabled: true
        same_site: lax

    trusted_proxies: '%env(TRUSTED_PROXIES)%'
    trusted_hosts: '%env(TRUSTED_HOSTS)%'
